import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <section>
          <div className="mx-auto max-w-screen-xl px-4 py-32 lg:flex lg:h-screen lg:items-center">
            <div className="mx-auto max-w-xl text-center">
              <h1 className="text-3xl font-extrabold sm:text-5xl">
                Server built with{" "}
                <Link
                  href={"https://go.dev/"}
                  className="text-blue-500 hover:underline"
                >
                  Go
                </Link>
                <strong className="font-extrabold text-red-700 sm:block">
                  Increase Conversion.
                </strong>
              </h1>

              <span className="mt-4 sm:text-xl sm:leading-relaxed">
                Available api endpoints:
                <ul className="mt-4 sm:text-xl sm:leading-relaxed">
                  <li>/api/users</li>
                  <li>/api/users/[userID]</li>
                  <li>/api/form</li>
                </ul>
              </span>

              <div className="mt-8 flex flex-wrap justify-center gap-4">
                <Link
                  className="block w-full rounded bg-red-600 px-12 py-3 text-sm font-medium text-white shadow hover:bg-red-700 focus:outline-none focus:ring active:bg-red-500 sm:w-auto"
                  href="http://monzim.com/"
                >
                  My Website
                </Link>
                <Link
                  className="block w-full rounded px-12 py-3 text-sm font-medium text-red-600 shadow hover:text-red-700 focus:outline-none focus:ring active:text-red-500 sm:w-auto"
                  href="/add"
                >
                  Add user data
                </Link>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
